name: CrazyEnvoy
author: BadBones69
main: me.badbones69.envoy.Main
version: ${version}
description: A crazy envoy plugin.
softdepend: [HolographicDisplays, PlaceholderAPI, MVdWPlaceholderAPI, Multiverse-Core, MultiWorld]
commands:
  envoy:
    description: Shows the next time till the next envoy.

permissions:
  envoy.bypass:
    description: Bypass all CrazyEnvoy permission.
    default: false
