name: '${name}'
main: '${group}.CrazyEnvoys'

version: '${version}'
api-version: '1.20'
description: '${description}'
website: '${website}'

folia-supported: true

dependencies:
  server:
    DecentHolograms:
     load: BEFORE
     required: false
     join-classpath: true
    FancyHolograms:
      load: BEFORE
      required: false
      join-classpath: true
    CMI:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
     load: BEFORE
     required: false
     join-classpath: true
    Oraxen:
      load: BEFORE
      required: false
      join-classpath: true
    Multiverse-Core:
     load: BEFORE
     required: false
     join-classpath: true
    MultiWorld:
      load: BEFORE
      required: false
      join-classpath: true
    MyWorlds:
      load: BEFORE
      required: false
      join-classpath: true
    WorldEdit:
      load: BEFORE
      required: false
      join-classpath: true
    WorldGuard:
      load: BEFORE
      required: false
      join-classpath: true